FROM registry.cn-hangzhou.aliyuncs.com/yab/protobuf

RUN go get -v -u google.golang.org/grpc
RUN go get -v -u github.com/ghodss/yaml
RUN go get -v -u github.com/golang/protobuf/protoc-gen-go
RUN go get -v -u github.com/benzfield/grpc-gateway/protoc-gen-grpc-gateway
RUN go get -v -u github.com/benzfield/grpc-gateway/protoc-gen-swagger
RUN go get -v -u github.com/jteeuwen/go-bindata/...
RUN go get -v -u github.com/elazarl/go-bindata-assetfs/...

CMD ["protoc"]
